---
- hosts: linux
  user: root

  vars:
    motd: "Welcome to RedHat Enterprise - Mr. Harish Ravipati"

  tasks:
    - name: Creating File
      file:
        path: /home/ubuntu/ravipati/Srikar.txt
        state: touch
      when: ansible_distribution == "Ubuntu"
    - name: In line Content
      copy:
        content: 'Hello AadithyaSrikar'
        dest: /home/ubuntu/ravipati/Srikar.txt
      when: ansible_distribution == "Ubuntu"
    - name: Copying file
      copy:
        src: /home/ubuntu/ansible/hosts
        dest: /home/ubuntu/ravipati
        mode: '0400'
      when: ansible_distribution == "Ubuntu"
    - name: motd
      copy:
        content: "{{motd}}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "RedHat"
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed