---
- hosts: ansible

  tasks:
    - name: gather ec2-facts
      ec2_instance_facts:
        region: us-east-2
      register: publicip
  
    - name: display public ip address
      debug:
        var: publicip.instances
      register: test2

    - name: waka waka
      debug:
        var: test2