---
- hosts: all
  user: root
  gather_facts: false

  tasks:
    - name: Installing Apache Tomcat
      get_url:
          dest: /home/ubuntu/
          url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.47/bin/apache-tomcat-8.5.47.tar.gz
    - name: Unzipping Apache Tomcat
      unarchive:
          src: /home/ubuntu/apache-tomcat-8.5.47.tar.gz
          dest: /home/ubuntu/
    - name: Enabling Apache Tomcat
      shell: nohup /home/ubuntu/apache-tomcat-8.5.47/bin/startup.sh
