---
- hosts: all
  user: root
  gather_facts: true

  tasks:
    - name: Installing Java
      yum:
        update_cache: yes
        name: openjdk-8-jdk
        state: present
      when:
        ansible_distribution == "RedHat"