---
- hosts: all
  tasks:
    - name: Centos Hostname
      debug:
        msg: >
             {% if ansible_hostname == "centos01" -%}
                This is ansible hostname for centos01
             {% elif ansible_hostname == "ubuntu01" -%}
                This is ansible hostname for ubuntu01
             {% else -%}
                This is Harish Ravipati {{ ansible_hostname }}
             {% endif %}

    - name: For loop
      debug:
        msg: >
             {% for entry in ansible_all_ipv4_addresses -%}
             My IP Addresses {{ loop.index }} = {{ entry }}
             {% endfor %}