---
- hosts: linux
  tasks:
    - name: Centos Hostname
      debug:
        msg: >
             --== Ansible Jinja2 if elif else statement ==--
             {% if ansible_hostname == "centos01" -%}
                  This is ansible hostname for centos01
             {% endif %}