---
- hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: update system
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Installing Nginx
      package:
        name: nginx
        state: present