---
- hosts: ubuntu
  become: yes
  gather_facts: true

  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present

    - name: Download web template
      get_url:
          dest: /home/ubuntu/
          url: https://www.free-css.com/assets/files/free-css-templates/download/page245/power.zip
          owner: ubuntu
          group: ubuntu

    - name: unzip
      unarchive:
          src: /home/ubuntu/power.zip
          dest: /home/ubuntu/
          remote_src: yes
    
    - name: copy files to nginx html directory
      copy: 
        src: /home/ubuntu/templatemo_508_power/*
        dest: /usr/share/nginx/html/
        remote_src: yes
      notify: restart nginx


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
