---
- hosts: ubuntu
  become: yes
  gather_facts: false

  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present

    - name: Download web template
      get_url:
          dest: /home/ubuntu/
          url: https://www.free-css.com/assets/files/free-css-templates/download/page245/power.zip
          owner: ubuntu
          group: ubuntu

    - name: unzip
      unarchive:
          src: /home/ubuntu/power.zip
          dest: /home/ubuntu/
          remote_src: yes
    
    - name: delete file
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent

    - name: copy files to nginx html directory
      copy: 
        src: /home/ubuntu/templatemo_508_power/
        dest: /var/www/html/
        remote_src: yes
      notify:
        - restart nginx
        - Check HTTP service


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: Check HTTP service
      uri:
        url: http://{{ ansible_default_ipv4.address }}
        status_code: 200
