---
- hosts: ubuntu01
  become: true

  tasks:
    - name: Creating Users
      user:
        name: "{{ item.1 }}"
        comment: "{{ item.1 | title }} {{ item.0.surname }}"
      with_subelements:
        - family:
            surname: ravipati
            members:
              - Harish
              - Sarayu
              - Aadithya
        - members