---
- hosts: ubuntu01
  become: true

  tasks:
    - name: Creating Users
      user:
        name: "{{ item.key }}"
        comment: "{{ item.value.surname }}"
      with_dict:
        Harish:
          surname: Ravipati
        Saidalli:
          surname: shaik
        Srikanth:
          surname: puttapaka