---
- hosts: ubuntu01
  become: true

  tasks:
    - name: Creating Users
      user:
        name: "{{ item.1 }}"
        comment: "{{ item.1 | title }} {{ item.0.surname }}"
        state: absent
      with_subelements:
        - family:
            surname: ravipati
            members:
              - Harish
              - Sarayu
              - Aadithya
        - members

---

- hosts: ubuntu01
  become: true

  tasks:
  
    - name: Creating a user directory
      file:
        dest: "/home/{{ item.0 }}/{{ item.1 }}"
        owner: "{{ item.0 }}"
        group: "{{ item.0 }}"
        state: directory
      with_nested:
        - [ Harish, Sarayu, Aadithya ]
        - [ photos, movies, documents ]