---
- hosts: ubuntu01
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Testing myname
      debug:
        msg: "{{ myname }}"
    - name: Family Details
      debug:
        msg: "{{ myfamily }}"
    - name: MOM Name
      debug:
        msg: "{{ myfamily.mom}, {myfamily.wife}, {myfamily.son }}"
    - name: My Hobbies
      debug:
        msg: "{{ myhobbies.1 }}"
    